title: "Level+1"
author: JackLeveledUp
email: JackLeveledUp@gmail.com
url: "https://levelplusone.com"
description: >
  Growth through games, anime, and culture

# navigation
navigation:
  - about.md

paginate: 6

# social
twitter: "JackLeveledUp"
twitch: "JackLeveledUp"
rss: true
# youtube_username: jekyll
# youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
# youtube_channel_name: CloudCannon

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate